### ISSUE TITLE
Help on ofx 0.10.1 windows

### ISSUE THREAD

**Issue by dvdrbls** [reginaflores/metaMethods#1]
Hello
I'm trying to build the project but it doesn't in this release of ofx

of_v0.10.1_msys2_release
fatal error: ofxThreadedImageLoader.h: No such file or directory
 #include "ofxThreadedImageLoader.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
 this is the message, i already download the ofxJSON and ofxProgressiveTextureLoad any ideas how can I make it run?
thanks!

**Comment by rf2030** [comment]
Hi! This project is very old and not maintained. I’m sure it doesn’t work anymore. Sorry!

**Comment by dvdrbls** [comment]
> 
> 
> Hi! This project is very old and not maintained. I’m sure it doesn’t work anymore. Sorry!

No problem, thanks anyway!
